const co = require('co');

const OneViewClient = require('..');
const config = require('./config');

// Create server profiles in OneView
// Tested only again 3.00 OneView
module.exports = function addProfile(ip) {
  return co(function*() {
    const client = new OneViewClient(ip, config.credential, true);
    yield client.login();

    const serverTypes = yield client.getAllMembers({
      uri: '/rest/server-hardware-types/',
    });
    const egs = yield client.getAllMembers({
      uri: '/rest/enclosure-groups',
    });
    const profiles = yield client.getAllMembers({
      uri: '/rest/server-profiles/',
    });
    console.log(`[${ip}] There exist ${profiles.length} profiles ${serverTypes.length} server-hardware type ${egs.length} enclosure groups`);

    const profileNames = new Set(profiles.map(profile => profile.name));
    let promises = [];
    // Add 100 empty profiles
    for(let i = 0; i < 100; i += 1) {
      const sht = serverTypes[i % serverTypes.length];
      const newProfileName = `empty-profile-${sht.name}-${Math.floor(i / serverTypes.length)}`;
      promises.push(co(function* creatProfileGen() {
        if (!profileNames.has(newProfileName)) {
          const postRes = yield client.post({
            uri: '/rest/server-profiles',
            resolveWithFullResponse: true,
            body: {
              name: newProfileName,
              type: 'ServerProfileV6',
              serverHardwareUri: null,
              serverHardwareTypeUri: sht.uri,
              enclosureGroupUri: egs[0].uri,
              serialNumberType: 'Virtual',
              iscsiInitiatorNameType: 'AutoGenerated',
              macType: 'Virtual',
              wwnType: 'Virtual',
              description: '',
              affinity: 'Bay',
              connections: [],
              bootMode: null,
              firmware: {
                manageFirmware: false,
                firmwareBaselineUri: '',
                forceInstallFirmware: false,
                firmwareInstallType: null,
              },
              bios: {
                manageBios: false,
                overriddenSettings: [],
              },
              hideUnusedFlexNics: true,
              iscsiInitiatorName: '',
              osDeploymentSettings: null,
              localStorage: {
                sasLogicalJBODs: [],
                controllers: [],
              },
              sanStorage: null,
            },
          }).catch(err => {
            console.log(`[${ip}] post profile error for ${newProfileName}, ${err.message}`);
            return null;
          });
          if (postRes) {
            console.log(`[${ip}] server profile is posted, task: ${postRes.headers.location}`);
            const profile = yield client.waitTaskComplete(postRes.headers.location).catch(err => {
              console.log(`[${ip}] server profile ${newProfileName} is not created because ${err.taskErrors ? JSON.stringify(err) : err.taskErrors[0].message}`);
              return null;
            });
            if (profile) {
              console.log(`[${ip}] server profile ${profile.name} is created`);
            }
          }
        }
      }));

      // concurrency
      if ((i + 1) % 16 === 0) {
        yield Promise.all(promises);
        promises = [];
      }
    }
  });
};

if (require.main === module) {
  module.exports(process.argv[2]).then(() => {
    console.log('Done');
  }).catch((err) => {
    console.error(`[${process.argv[2]}] ${err.message}, stack:${err.stack}`);
  });
}
